language: node_js
sudo: false
node_js:
  - 6

cache:
  directories:
    - ~/.npm
    - ~/.yarn-cache

git:
  depth: 10

before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm i -g npm@^5

install:
  - npm i

script:
  - ./bin/docdash ./node_modules/lodash/lodash.js output.md toc=categories url=https://github.com/lodash/lodash/blob/master/lodash.js
  - cat output.md
