language: node_js
sudo: false
node_js:
  - 6

cache:
  directories:
    - ~/.npm
    - ~/.yarn-cache

git:
  depth: 10

before_install:
  - nvm use $TRAVIS_NODE_VERSION
  - npm i -g npm@^5

install:
  - npm i

script:
  - ./bin/docdash ./node_modules/docdash/docdash.js output.md toc=categories url=https://github.com/flavioespinoza/docdash/blob/master/docdash.js
  - cat output.md
